# Generated by Django 3.2 on 2022-05-26 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_similartoadvert'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='advert',
            name='publications',
            field=models.ManyToManyField(blank=True, null=True, to='tests.Publication'),
        ),
    ]
