# Generated by Django 5.0.9 on 2024-12-12 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0004_advert_publications"),
    ]

    operations = [
        migrations.AddField(
            model_name="simplepage",
            name="airtable_record_id",
            field=models.CharField(blank=True, db_index=True, max_length=35),
        ),
    ]
